services:
  - type: web
    name: candidate-sourcing
    env: node
    buildCommand: |
      apt-get update && apt-get install -y chromium-browser
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      # Add your required environment variables here or set them in the Render dashboard
      # - key: GEMINI_API_KEY
      #   value: your_gemini_api_key
      # - key: SERPER_API_KEY
      #   value: your_serper_api_key
      # - key: LINKEDIN_USERNAME
      #   value: your_linkedin_username
      # - key: LINKEDIN_PASSWORD
      #   value: your_linkedin_password
    disk:
      name: data
      mountPath: /data
    autoDeploy: false
